// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CPIXMEDIAAUDIODOCTRACES_H__
#define __CPIXMEDIAAUDIODOCTRACES_H__

#define KOstTraceComponentID 0x20029ab9

#define CCPIXMEDIAAUDIODOC_GETCPIXDOCUMENTL_ENTRY 0x8a0001
#define CCPIXMEDIAAUDIODOC_GETCPIXDOCUMENTL_EXIT 0x8a0002


#endif

// End of file

