// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CPIXMEDIAVIDEODOCTRACES_H__
#define __CPIXMEDIAVIDEODOCTRACES_H__

#define KOstTraceComponentID 0x20029aba

#define CCPIXMEDIAVIDEODOC_GETCPIXDOCUMENTL_ENTRY 0x8a0001
#define CCPIXMEDIAVIDEODOC_GETCPIXDOCUMENTL_EXIT 0x8a0002


#endif

// End of file

